= The FloorPlan library

FloorPlan is a library to model a heterogeneous software system's specification
for testing.

A challenge in system level automated testing is in modeling SUT in a way where
you can

. deploy your SUT automatically and repeatably
. verify deployment variations.
. deploy your SUT in various physical environments (dev, stg, prod, local) while
 a test scenario can work transparently.
. reuse and run your tests by combinating your test scenario, environments, and
 deployment from your repertoire.

at the same time.

This library gives a programmable way to achieve those. For more detail,
see our https://github.com/dakusui/floorplan/wiki[our wiki].

Inside `floorplan`

[ditaa]
----
                                    +---------------------------+             +-------+
Component layout planning phase=--->|FloorPlanDescriptor.Builder|<>---------->|Profile|
                                    +-------------+-------------+  1       1  +-------+
                                                  |                                ^ 1
                                                  :                                |
                                                  V                                | 1
                                        +---------+---------+              1   +---+--+
                                        |FloorPlanDescriptor|        +-------->|Policy|
                                        +---------+---------+        |         +------+
                                                  ^                  |
                                                  |                  |
                                       +----------+-----------+   1  |      +------------+
                                       |                      |<>----+      |            |
                                       |                      |             |            |
                                       |FloorPlanConfigurator |[ref]<>----->|Configurator|
                                       |                      |             |            |
                                       |                      |             |            |
                                       +----------+-----------+          1  +------+-----+
                                                  |build()                         |configure()
                                                  :                                :
                                  +---------------|--------------------------------|--------------------------+
                                  |               |                                :                          |
                                  |               :                                :                          |
                                  |               V                                V                          |
                                  |         +----------+                      +---------+                     |
                                  |         |          |                      |         |                     |
Action building phase=----------->|         |FloorPlan |[ref]<>-------------->|Component| (Immutable)         |
                                  |         |          |                      |         |                     |
                                  |         +----------+                   1  +----+----+                     |
                                  |                                                |                          |
                                  |                                    +-----------+-----------+              |
                                  |                                    |                       |              |
                                  |                            +-------+--------+      +-------+--------+     |
                                  |                            |ActualComponent1|      |ActualComponent2|     |
                                  |                            +----------------+      +----------------+     |
                                  |                             method1() Action        method1() Action      |
                                  |                             method2() Action        method2() Action      |
                                  |                                    |                       |              |
                                  +------------------------------------:-----------------------:--------------+
                                                                       |                       |
                                  +------------------------------------:-----------------------:--------------+
                                  |                                    |                       |              |
                                  |                                    V                       V              |
                                  |                                +------+                +------+           |
Action performing phase---------->|                                |Action|                |Action|           |
                                  |                                +------+                +------+           |
                                  |                                                                           |
                                  +---------------------------------------------------------------------------+
----


== Installation and how to use it

Following is maven coordinate.

[source,xml]
----
  <dependency>
    <groupId>com.github.dakusui</groupId>
    <artifactId>floorplan</artifactId>
    <version>[5.0.0)</version>
  </dependency>
----

== Building FloorPlan library.

This library is built and tested with following JDK and Maven.
`
// JDK
java version &quot;1.8.0_172&quot;
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)
// Maven
Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-25T04:49:05+09:00)
`

To build this, clone this repo and run following maven command.

[source]
----
// clone
$ git clone https://github.com/dakusui/floorplan.git
// build and test
$ mvn clean compile test

----

= References

* https://github.com/dakusui/floorplan/wiki[1]: FloorPlan Wiki